"""Object storage for generated files (exports), behind one small interface.

A worker writes the file; a browser downloads it. So the contract is: ``put``
bytes under a key, then issue a **short-lived signed URL** for it. File bytes
never flow back through the API, and no link is permanent.

* :class:`S3Storage` — any S3-compatible store (AWS S3, MinIO, Cloudflare R2, ...).
  Download links are presigned GETs. Presigning is offline (no network call) and
  uses the *public* endpoint: a SigV4 signature covers the Host header, so the
  browser must hit exactly the host the URL was signed for, even when workers
  reach the store at a private address.
* :class:`LocalStorage` — a local directory with the same contract: an expiring
  HMAC-signed URL served by ``GET /api/v1/export-files/...``. For development
  without an object store, and for tests. The API and worker must share the
  directory.
"""
from __future__ import annotations

import hashlib
import hmac
import os
import re
import time
from functools import lru_cache
from pathlib import Path
from typing import Any, Protocol
from urllib.parse import quote, urlencode

from ..config import Settings, get_settings

# Keys are generated by the app, never taken from users, but the local backend
# maps them onto the filesystem, so they are validated strictly anyway: plain
# segments only (no leading dot, so no "." or ".." segments), no absolute paths.
_SEGMENT = r"[A-Za-z0-9_-][A-Za-z0-9._-]*"
_KEY_RE = re.compile(rf"^{_SEGMENT}(?:/{_SEGMENT})*$")
_MAX_KEY_LEN = 512


def check_key(key: str) -> str:
    if len(key) > _MAX_KEY_LEN or not _KEY_RE.fullmatch(key):
        raise ValueError(f"invalid object key: {key!r}")
    return key


def content_disposition(filename: str) -> str:
    """``attachment`` with an ASCII fallback name plus the RFC 5987 UTF-8 form."""
    fallback = re.sub(r"[^A-Za-z0-9._ -]", "_", filename) or "download"
    return f"attachment; filename=\"{fallback}\"; filename*=UTF-8''{quote(filename, safe='')}"


class ObjectStorage(Protocol):
    def put(self, key: str, data: bytes, *, content_type: str) -> None: ...

    def signed_url(
        self, key: str, *, filename: str, content_type: str, expires_in: int
    ) -> str: ...

    def delete(self, key: str) -> None: ...


# --------------------------------------------------------------------------- #
# S3-compatible                                                                #
# --------------------------------------------------------------------------- #
class S3Storage:
    def __init__(
        self,
        *,
        bucket: str,
        region: str = "us-east-1",
        endpoint_url: str | None = None,
        public_endpoint_url: str | None = None,
        access_key_id: str | None = None,
        secret_access_key: str | None = None,
        create_bucket: bool = False,
    ) -> None:
        import boto3  # lazy: only S3 deployments pay for the import
        from botocore.config import Config

        config = Config(
            signature_version="s3v4",
            # Path-style (host/bucket/key) for custom endpoints: MinIO and most
            # S3-compatibles don't serve per-bucket DNS names.
            s3={"addressing_style": "path" if endpoint_url else "auto"},
            connect_timeout=5,
            read_timeout=60,
            retries={"max_attempts": 3, "mode": "standard"},
        )

        def client(endpoint: str | None) -> Any:
            # Credentials left as None fall through to the default AWS chain
            # (environment, instance/task role).
            return boto3.client(
                "s3",
                endpoint_url=endpoint,
                region_name=region,
                aws_access_key_id=access_key_id,
                aws_secret_access_key=secret_access_key,
                config=config,
            )

        self.bucket = bucket
        self.region = region
        self.client = client(endpoint_url)
        public = public_endpoint_url or endpoint_url
        self.signing_client = self.client if public == endpoint_url else client(public)
        self._bucket_ready = not create_bucket

    def _ensure_bucket(self) -> None:
        """Create the bucket on first write (dev convenience, S3_CREATE_BUCKET)."""
        if self._bucket_ready:
            return
        from botocore.exceptions import ClientError

        try:
            self.client.head_bucket(Bucket=self.bucket)
        except ClientError as exc:
            if exc.response.get("Error", {}).get("Code") not in ("404", "NoSuchBucket", "NotFound"):
                raise
            extra = (
                {}
                if self.region == "us-east-1"
                else {"CreateBucketConfiguration": {"LocationConstraint": self.region}}
            )
            try:
                self.client.create_bucket(Bucket=self.bucket, **extra)
            except ClientError as create_exc:  # another worker won the race
                if create_exc.response.get("Error", {}).get("Code") != "BucketAlreadyOwnedByYou":
                    raise
        self._bucket_ready = True

    def put(self, key: str, data: bytes, *, content_type: str) -> None:
        self._ensure_bucket()
        self.client.put_object(
            Bucket=self.bucket, Key=check_key(key), Body=data, ContentType=content_type
        )

    def signed_url(self, key: str, *, filename: str, content_type: str, expires_in: int) -> str:
        return str(
            self.signing_client.generate_presigned_url(
                "get_object",
                Params={
                    "Bucket": self.bucket,
                    "Key": check_key(key),
                    # Response overrides are covered by the signature, so the
                    # download name and type can't be altered by the holder.
                    "ResponseContentDisposition": content_disposition(filename),
                    "ResponseContentType": content_type,
                },
                ExpiresIn=expires_in,
            )
        )

    def delete(self, key: str) -> None:
        self.client.delete_object(Bucket=self.bucket, Key=check_key(key))


# --------------------------------------------------------------------------- #
# Local directory (dev + tests)                                                #
# --------------------------------------------------------------------------- #
class LocalStorage:
    URL_PREFIX = "/api/v1/export-files"

    def __init__(self, root: str | Path, *, secret: str) -> None:
        self.root = Path(root).resolve()
        # Derived, not the raw secret: a leaked link never helps forge a JWT.
        self._mac_key = hmac.new(
            secret.encode(), b"vendor-risk/local-export-url", hashlib.sha256
        ).digest()

    def path_for(self, key: str) -> Path:
        path = (self.root / check_key(key)).resolve()
        if not path.is_relative_to(self.root):
            raise ValueError(f"object key escapes the storage root: {key!r}")
        return path

    def put(self, key: str, data: bytes, *, content_type: str) -> None:
        path = self.path_for(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        partial = path.with_name(path.name + ".part")
        partial.write_bytes(data)
        os.replace(partial, path)  # atomic: a reader never sees half a file

    def delete(self, key: str) -> None:
        self.path_for(key).unlink(missing_ok=True)

    def _signature(self, key: str, exp: int, filename: str, content_type: str) -> str:
        message = "\n".join((key, str(exp), filename, content_type)).encode()
        return hmac.new(self._mac_key, message, hashlib.sha256).hexdigest()

    def signed_url(
        self,
        key: str,
        *,
        filename: str,
        content_type: str,
        expires_in: int,
        now: float | None = None,
    ) -> str:
        exp = int((time.time() if now is None else now) + expires_in)
        query = urlencode(
            {
                "exp": exp,
                "name": filename,
                "type": content_type,
                "sig": self._signature(check_key(key), exp, filename, content_type),
            }
        )
        return f"{self.URL_PREFIX}/{key}?{query}"

    def verify(
        self,
        key: str,
        *,
        exp: int,
        filename: str,
        content_type: str,
        sig: str,
        now: float | None = None,
    ) -> bool:
        if exp < (time.time() if now is None else now):
            return False
        return hmac.compare_digest(sig, self._signature(key, exp, filename, content_type))


# --------------------------------------------------------------------------- #
# Factory                                                                      #
# --------------------------------------------------------------------------- #
def build_storage(settings: Settings) -> ObjectStorage:
    kind = settings.export_storage.lower()
    if kind == "s3":
        # `or None`: a blank `S3_ENDPOINT_URL=` line in .env means "unset" (AWS
        # defaults), not an empty endpoint.
        return S3Storage(
            bucket=settings.s3_bucket,
            region=settings.s3_region,
            endpoint_url=settings.s3_endpoint_url or None,
            public_endpoint_url=settings.s3_public_endpoint_url or None,
            access_key_id=settings.s3_access_key_id or None,
            secret_access_key=settings.s3_secret_access_key or None,
            create_bucket=settings.s3_create_bucket,
        )
    if kind == "local":
        return LocalStorage(settings.export_local_dir, secret=settings.jwt_secret)
    raise ValueError(f"EXPORT_STORAGE must be 'local' or 's3', not {settings.export_storage!r}")


@lru_cache
def get_storage() -> ObjectStorage:
    """The process-wide store (boto3 clients are thread-safe and reusable)."""
    return build_storage(get_settings())
