"""Operational tables: sync runs (evolves the demo's ingest_runs), audit log, and
background export jobs."""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    JSON,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from .base import (
    Base,
    ExportFormat,
    ExportStatus,
    SyncStatus,
    export_format_enum,
    export_status_enum,
    sync_status_enum,
)

JSONVariant = JSON().with_variant(JSONB, "postgresql")


class SyncRun(Base):
    __tablename__ = "sync_runs"

    id: Mapped[int] = mapped_column(primary_key=True)
    # Nullable: a shared-cache sync run driven by the system key is not org-scoped.
    org_id: Mapped[int | None] = mapped_column(
        ForeignKey("organizations.id", ondelete="CASCADE"), nullable=True, index=True
    )
    status: Mapped[SyncStatus] = mapped_column(
        sync_status_enum, nullable=False, default=SyncStatus.running
    )
    mode: Mapped[str] = mapped_column(String(16), nullable=False, default="live")
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    vendors_attempted: Mapped[int | None] = mapped_column(Integer, nullable=True)
    vendors_succeeded: Mapped[int | None] = mapped_column(Integer, nullable=True)
    cves_upserted: Mapped[int | None] = mapped_column(Integer, nullable=True)
    error_detail: Mapped[str | None] = mapped_column(Text, nullable=True)


class AuditLog(Base):
    __tablename__ = "audit_log"

    id: Mapped[int] = mapped_column(primary_key=True)
    org_id: Mapped[int] = mapped_column(
        ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    actor_user_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    action: Mapped[str] = mapped_column(String(100), nullable=False)
    target_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    target_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    extra: Mapped[dict | None] = mapped_column(JSONVariant, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, index=True
    )


class ExportJob(Base):
    """A portfolio export generated by a worker and kept in object storage.

    The file itself never lives in the database: ``object_key`` points into the
    bucket, and downloads go through a short-lived signed URL issued per request.
    After ``expires_at`` the purge task deletes the object and marks the job
    ``expired``; the row stays as history.
    """

    __tablename__ = "export_jobs"
    __table_args__ = (Index("ix_export_jobs_org_id_created_at", "org_id", "created_at"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    org_id: Mapped[int] = mapped_column(
        ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False
    )
    requested_by_user_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    format: Mapped[ExportFormat] = mapped_column(export_format_enum, nullable=False)
    status: Mapped[ExportStatus] = mapped_column(
        export_status_enum, nullable=False, default=ExportStatus.queued
    )
    filename: Mapped[str | None] = mapped_column(String(200), nullable=True)
    content_type: Mapped[str | None] = mapped_column(String(100), nullable=True)
    object_key: Mapped[str | None] = mapped_column(String(512), nullable=True)
    size_bytes: Mapped[int | None] = mapped_column(Integer, nullable=True)
    error: Mapped[str | None] = mapped_column(String(500), nullable=True)  # user-safe text
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
